### ISSUE TITLE
Error trying to use recipe

### ISSUE THREAD

**Issue by dlong500** [jsreport/toner-html-to-xlsx#1]
I'm trying to use the html-to-xlsx recipe with toner and am getting the following error:
`unspecified-error Cannot find module 'toner-html-to-xlsx'`

I have installed the module via npm and am using the following line to register the recipe:
`toner.recipe("html-to-xlsx", require("toner-html-to-xlsx")());`

What am I doing wrong?

**Comment by pofider** [comment]
This was caused by wrongly uploaded npm module.

Please update to latest `toner-html-to-xlsx` 0.1.2 and it should work.
